- id: 1
  range: 〜10万円以下
- id: 2
  range: 11〜20万円
- id: 3
  range: 21〜30万円
- id: 4
  range: 31〜50万円
- id: 5
  range: 51〜100万円
- id: 6
  range: 101〜300万円
- id: 7
  range: 301〜500万円
- id: 8
  range: 501〜1000万円
- id: 9
  range: 1001〜2000万円
- id: 10
  range: 2001〜3000万円
- id: 11
  range: 3001万円以上〜